# Generated by Django 5.2.4 on 2025-07-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.TextField()),
                ('mesa', models.IntegerField(max_length=24)),
                ('mesero', models.CharField(max_length=200)),
                ('total', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='menu_ejecutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('sopa', models.CharField(max_length=200)),
                ('plato_principal', models.CharField(max_length=200)),
                ('jugo', models.CharField(max_length=200)),
                ('precio', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio_carta', models.IntegerField(max_length=10)),
                ('cantidad', models.IntegerField(max_length=200)),
                ('alternativa', models.BooleanField()),
            ],
        ),
    ]
