# Generated by Django 5.2.4 on 2025-07-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_ejecutivo',
            name='precio_alternativo',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
