# Generated by Django 5.2.4 on 2025-07-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiAPP', '0002_menu_ejecutivo_precio_alternativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('rol', models.CharField(choices=[('mesero', 'Mesero'), ('admin', 'Administrador')], max_length=10)),
            ],
        ),
    ]
