# Generated by Django 5.2.4 on 2025-07-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiAPP', '0003_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='mesa',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.IntegerField(),
        ),
    ]
