# Generated by Django 5.2.4 on 2025-07-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiAPP', '0004_alter_factura_mesa_alter_factura_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='mesa',
            field=models.IntegerField(max_length=24),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.IntegerField(max_length=10),
        ),
    ]
