# Generated by Django 5.2.4 on 2025-07-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiAPP', '0005_alter_factura_mesa_alter_factura_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_ejecutivo',
            name='tipo',
            field=models.CharField(default='Ejecutivo', max_length=200),
        ),
    ]
