# Generated by Django 5.2.4 on 2025-07-31 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiAPP', '0006_menu_ejecutivo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='mesero',
        ),
        migrations.AlterField(
            model_name='factura',
            name='mesa',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='menu_ejecutivo',
            name='precio_alternativo',
            field=models.IntegerField(default=0),
        ),
    ]
