# Generated by Django 5.2.4 on 2025-07-31 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiAPP', '0007_remove_factura_mesero_alter_factura_mesa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(default='Alternativa', max_length=200)),
                ('sopa', models.CharField(max_length=200)),
                ('plato_principal', models.CharField(max_length=200)),
                ('jugo', models.CharField(max_length=200)),
                ('precio_alternativo', models.IntegerField(default=0)),
            ],
        ),
    ]
