# Generated by Django 5.2.4 on 2025-07-31 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiAPP', '0008_alternativa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternativa',
            old_name='plato_principal',
            new_name='alternativa',
        ),
    ]
