# Generated by Django 5.2.4 on 2025-07-31 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiAPP', '0009_rename_plato_principal_alternativa_alternativa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternativa',
            old_name='alternativa',
            new_name='plato_alternativa',
        ),
    ]
