# Generated by Django 5.2.4 on 2025-08-01 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiAPP', '0010_rename_alternativa_alternativa_plato_alternativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_ejecutivo',
            name='precio_alternativo',
        ),
    ]
