# Generated by Django 5.2.4 on 2025-08-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiAPP', '0011_remove_menu_ejecutivo_precio_alternativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='producto',
            field=models.JSONField(),
        ),
    ]
