# Generated by Django 5.2.4 on 2025-08-01 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiAPP', '0012_alter_factura_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='producto',
            new_name='productos',
        ),
    ]
